### ISSUE TITLE
vista filtros para Busquedas avanzadas

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-frontend#16]
**_VISTA ESTÁTICA, SIN FUNCIONALIDAD_**

**_COMO_** desarrollador **_QUIERO_** maquetar la vista de búsqueda avanza **_PARA_** poder navegar y acceder a dicha vista de "filtros de búsquda avanzada", teniendo presente que se busca a futuro:

> **_COMO_** usuario logeado **_QUIERO_** navegar a travez de botón 'filtros' (embudo) a la pantalla de filtros de búsqueda avanzada **_PARA_** acceder a las distintas opciones de la herramienta búsqueda avanzada.

Componentes y átomos asociados:

> - [x] Reutilizar - Header, issue #22 

- [x] Sección 'Juegos en común' (Título, input de búsqueda, listado seleccionado)
- [x] Sección 'Reseña" (Título, barra selectora)
- [x] Sección "Disponibilidad horaria" (Títulos, selectores/botones días, y selectores/botones horas).
- [x] Sección "Aplicar - Limpiar" (botonera).

![Image](https://github.com/Siuss/gamerly-frontend/assets/30749611/c48f3985-f29b-4036-b899-3f1a9c488cf0)

**Comment by Siuss** [comment]
Se crea la rama #16 para avanzar con este tarea. @rodripavon97

**Comment by rodripavon97** [comment]
Si

**Comment by Siuss** [comment]
En el commit de ayer, [729b74b](https://github.com/Siuss/gamerly-frontend/commit/729b74b6537e4529dad0f36268f6b31549dff771), para la constricción de la vista @rodripavon97 recomienda:
- Tener presente los componentes se exportan e importan.
- El trabajar en un paradigma funcional, amerita respetar el orden secuencial.
- Para el uso `props.children`, en caso, sobre la iteración de una lista, para presentar en la vista como:
`<MiEtiqueta key={item.id}> {item.name} </MiEtiqueta>`

**Comment by rodripavon97** [comment]
Falta el input range (buscalo) y revisar el css para insertar la estrella

**Comment by Siuss** [comment]
En este commit [ec518bb](https://github.com/Siuss/gamerly-frontend/commit/ec518bb4377a577f357a9f76532a2bbc815a0013). se completa el estilo **a la lista de píldoras** para que realicen **el salto en la línea**, según documentación: **[FlexWrap](https://reactnative.dev/docs/flexbox?language=javascript#flex-wrap)**

**Comment by Siuss** [comment]
El elemento _slider_ ó _imput range_, actualmente, NO pertence al _core_ de componentes de _React Native_.

Una de las alternativa es crearlo desde cero.

Otra, es utilizar una opción que plantea la siguiente solución planteada por una comunidad _React Native_  en [@react-native-community/slider](https://www.npmjs.com/package/@react-native-community/slider). Según el siguiente comando, procedo a instalar:

`npm install @react-native-community/slider --save`

**Comment by Siuss** [comment]
[4eb0e3c](https://github.com/Siuss/gamerly-frontend/commit/4eb0e3c0ed3afe42901c418d69f8d34786f7fbb2): Se finalizan algunos estilos para la presentación de esta **vista estática** 'BusquedaAvanzada'.

**Comment by Siuss** [comment]
@rodripavon97 Se genera solicitud de _Pull Request_ **[#49](https://github.com/Siuss/gamerly-frontend/pull/49)**. Una vez se pueda conciliar la solicitud, se procederá a cerrar el ticket.
