### ISSUE TITLE
pantalla de vista de Perfil usuario

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-frontend#17]
**_VISTA ESTÁTICA, NO INCLUYE EDICIÓN_**

**_COMO_** desarrollador **_QUIERO_** integrar los distintos componentes de Perfil de usuario **_PARA_** que se puede visualizar la información del usuario. Considerar qué:

> **_COMO_** usuario logeado **_QUIERO_** navegar a la vista de perfil **_PARA_** visualizar su datos o la configuración de ellos.

Componentes:

> - [x]  Reutilizar - Header: ver issue 9 #22.

> - [x]  Reutilizar - Componente Perfil Usuario: ver issue #29.

> - [x]  Reutilizar - Navegation button ver #25.

![Image](https://github.com/Siuss/gamerly-frontend/assets/30749611/9e83ee6a-84df-4ee7-bcc4-5c44be5a5e63)

**Comment by rodripavon97** [comment]
@veronicacarbonelli te asigne con @julii0m para que te de una mano

**Comment by rodripavon97** [comment]
perfil al 100%, cierro el issue y de paso borro el branch
