### ISSUE TITLE
pantalla de vista de Resenias

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-frontend#18]
**_COMO_** desarrollador **_QUIERO_** integrar los distintos componentes de Reseñas **_PARA_** a la vista esta pantalla.

> **_COMO_** usuario logeado **_QUIERO_** navegar a través de un elemento de jugador (card) **_PARA_** a la vista esta pantalla.

A continuación, los átomos de la vista:

> - [x] Header:  ver issue #22.

> - [x] Componente card elemento Resenia: ver issue #28.

> - [x] _Navegation button_, ver issue #25.

> - [x] Reutilizar - Utiliza datos mockeados #23 

![Image](https://github.com/Siuss/gamerly-frontend/assets/30749611/83a4ada4-c4a1-4624-ae03-a34dfab7aa16)

**Comment by rodripavon97** [comment]
falta alg
