### ISSUE TITLE
Implementar la busqueda de jugadores a traves de los filtros avanzados

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-frontend#2]
- Como usuario, quiero buscar otros jugadores que jueguen a mi juego favorito.
- Como usuario, quiero buscar otros jugadores que tengan un nivel de habilidad similar al mío.
- Como usuario, quiero buscar otros jugadores que estén disponibles para jugar en mi horario.

**Comment by rodripavon97** [comment]
@stephaniepazos89 como va esa parte?
