### ISSUE TITLE
diseniar la interfaz de resenias

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-frontend#5]
![Image](https://github.com/Siuss/gamerly-frontend/assets/30749611/710535b1-1603-441b-b724-518e77f27c89)

![Image](https://github.com/Siuss/gamerly-frontend/assets/48970101/f24e3578-141f-4088-99b1-1cd139c2af7c)

**Comment by rodripavon97** [comment]
consultar @stephaniepazos89 que idea propone en este issue. por las dudas te asignamos
