### ISSUE TITLE
Implementar la interfaz de resenias

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-frontend#6]
![Image](https://github.com/Siuss/gamerly-frontend/assets/63320128/f84ead13-2e2e-4c7d-b559-94ccdd15420f)

**Comment by rodripavon97** [comment]
faltaria el agregar resenias

**Comment by rodripavon97** [comment]
@Siuss el tema de backend no tendriamos que dejar en el sprint 4?
