### ISSUE TITLE
Adios gradiente background en componentes

### ISSUE THREAD

**Issue by Siuss** [Siuss/gamerly-frontend#66]
COMO desarrollador QUIERO refactorizar los átomos, componentes y vistas que usan el componente **gradiente** _background_ PARA modificar a un fondo de color sólido, una vez .

**Comment by Siuss** [comment]
> Del archivo Card.jsx, se eliminaron 2 importaciones que no se usaban:
> 
> - Icons desde AntDesign
> - Gradiente desde Gradiente.jsx

**Comment by Siuss** [comment]
Se avanza con el resto la refactorización para sacar el gradiente.  Se genera el PR  **[#89](https://github.com/Siuss/gamerly-frontend/pull/89)** para cerrar el ticket.

@rodripavon97 

## Cerrar el ticket una vez conciliado el PR, por favor.

Ahora:

![Image](https://github.com/Siuss/gamerly-frontend/assets/30749611/aa6df94d-9974-4733-8303-f564d9367e9b)

<details><summary>Antes</summary>
<p>

![Image](https://github.com/Siuss/gamerly-frontend/assets/30749611/801078e6-b45c-4cd3-a82f-dd13f1e81749)

</p>
</details>

**Comment by Siuss** [comment]
Rama eliminada @rodripavon97

**Comment by rodripavon97** [comment]
Dale Diego, yo ahora marco el ticket completado
