### ISSUE TITLE
agregar en el front la conexion al endpoint comunidad

### ISSUE THREAD

**Issue by rodripavon97** [Siuss/gamerly-frontend#70]
necesito que esa parte este rapido para ver si funciona

**Comment by Siuss** [comment]
Se entiende que: COMO desarrollador QUIERO implementar el servicio a 'Comunidades' PARA obtener desde la BB.DD. el listado de las comunidades para unirse.

> COMO usuario QUIERO acceder a 'Comunidades' PARA obtener el listado de comunidades disponibles para unirme.

![Image](https://github.com/Siuss/gamerly-frontend/assets/30749611/52a90669-a9a4-4121-8de2-142b2983a469)

**Comment by Siuss** [comment]
@rodripavon97 @berardibraian23 @stephaniepazos89 @veronicacarbonelli 
## Necesito su ayuda:

Se plantea el endpoint, propuesta de solución en los archivos:

-  [ComunidadesService.js](https://github.com/Siuss/gamerly-frontend/blob/70-agregar-en-el-front-la-conexion-al-endpoint-comunidad/src/services/ComunidadesService.js) (**nuevo**).
- [Comunidad.jsx](https://github.com/Siuss/gamerly-frontend/blob/70-agregar-en-el-front-la-conexion-al-endpoint-comunidad/src/componentes/vistas/Comunidad.jsx)

Me encuentro con el error de que la función 'obtenerComunidades' no es reconocidad como función.

![Image](https://github.com/Siuss/gamerly-frontend/assets/30749611/ea94e27a-c9c7-45f2-8819-dba0fae58d21)

Hice las validaciones sugeridas: 
> El mensaje de error de la consola DevTools indica un problema con la función `obtenerComunidades`. Aquí hay una explicación y cómo solucionarlo:
> - **Función no definida**: El error `TypeError: (0 , _ComunidadesService.obtenerComunidades) is not a function` sugiere que `obtenerComunidades` no está definida o no se importó correctamente.
> - **Revisar importaciones**: Asegúrate de que `obtenerComunidades` esté definida en `_ComunidadesService` y que la importación sea correcta en `Comunidad.jsx`.
> - **Verificar exportaciones**: Confirma que `obtenerComunidades` se exporta correctamente desde el archivo de servicio.
> - **Corregir código**: Si `obtenerComunidades` es una función, corrige la importación/exportación. Si no lo es, revisa la lógica donde se supone que es una función.

Pero el problema se mantiene. ¿Con quién lo puedo revisar? La rama es [70-agregar-en-el-front-la-conexion-al-endpoint-comunidad](https://github.com/Siuss/gamerly-frontend/tree/70-agregar-en-el-front-la-conexion-al-endpoint-comunidad)

**Comment by rodripavon97** [comment]
El problema es que no llamas al archivo service tenes que importar la clase ComunidadService y luego en el componente es ComunidadService.obtenerComunidades

**Comment by rodripavon97** [comment]
En el array del useEffect le tendrías que pasar comunidad que es el está en el useState

**Comment by Siuss** [comment]
- https://github.com/Siuss/gamerly-frontend/issues/70#issuecomment-2175032386: En la línea 6 está la importación.
- https://github.com/Siuss/gamerly-frontend/issues/70#issuecomment-2175034396: Hace una referencia doble al mismo error, si está agregado al array.

Gracias @rodripavon97 
### Si notan alguna otra inconsistencia o ven en qué cometo mi error, comentenmé. Sigo investigando.

**Comment by rodripavon97** [comment]
Dale si veo algún error te aviso

**Comment by Siuss** [comment]
Encontré el error, tenía que ver la importación como @rodripavon97 antes me habías sugerido. Gracias por el aporte.

> - Estaba importando la función `obtenerComunidade` desde el archivo `Comunidad.jsx`, pero **no la estaba exportando esa función**. 
> - Como esta función es parte de un diccionario desde `ComunidadService.js` que se sí se exporta, **es ese diccionario el que debe ser importado** `COMUNIDADES_SERVICE`.
> 
> ## Implementación y exportación en `ComunidadesService.js`:
> ```
> const obtenerComunidades = async ( ) => { const response = await axios.get( ... ); };`
> export const COMUNIDADES_SERVICE = { obtenerComunidades };`
> ```
> ## Importación e implementación en `Comunidad.jsx`:
> ```
> import { COMUNIDADES_SERVICE } from "../../services/ComunidadesService";
> 
> // Luego puedes invocar obtenerComunidades así:
> COMUNIDADES_SERVICE .obtenerComunidades().then(comunidades => {
>   /* Haz algo con las comunidades */
> }).catch(error => {
>   /* Maneja el error */
> });
> ```

**Comment by Siuss** [comment]
@rodripavon97 Se realizó el PR #90 para repo de _front-end_.

@berardibraian23 @veronicacarbonelli @stephaniepazos89 @julii0m @alangomez900 hay cambios en la rama de _development_.


Por favor, solicitarme: 

- ### Validar la implementación.
- ### Validar que la rama se elimina al conciliar el PR.
- ### Validar que la tarea esté en estado finalizado.

**Comment by Siuss** [comment]
Se eliminó la rama.
